### ISSUE TITLE
Einsatzdateiexporter

### ISSUE THREAD

**Issue by CodingAnonymous** [OpenFireSource/AlarmWorkflow#129]
Hallo,

das Programm funktioniert super. Nur der Einsatzdateiexporter funktioniert meiner Meinung nach nicht. Ich habe ihn auf aktiv geschaltet und ihn auch im Backend > Engine aktiviert. Als Zieldatei wurde der Desktop ausgewählt. Die Zieldatei, also die .txt Datei, wenn nicht besteht wird diese nicht automatisch erstellt, wenn die Zieldatei besteht wird diese auch nicht bearbeitet. Wie kann ich das beheben?

Vielen Dank schon im Voraus!

**Comment by chrishensel** [comment]
Es muss eine **Datei** angegeben werden; kein Ordner. Also z. B. "D:\Alarmtext.txt".

Ansonsten: Welchen Fehler gibt es? Bitte die relevanten Teile aus der Logdatei hier posten.

**Comment by chrishensel** [comment]
Der Fehler konnte nicht reproduziert werden. 

Wenn der Fehler erneut auftritt, bitte eine ausführliche Beschreibung und Logfile anhängen.
