### ISSUE TITLE
Supportende .Net 4.5.1

### ISSUE THREAD

**Issue by Angreifer2** [OpenFireSource/AlarmWorkflow#131]
Hi, 
da laut
http://blogs.msdn.com/b/dotnet/archive/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1.aspx
der Support für .Net 4.5.1 endet würde ich einen Umstieg auf 4.5.2 oder bevorzugt gleich 4.6 empfehlen.
LG

**Comment by chrishensel** [comment]
Ja, kann man machen.

**Comment by chrishensel** [comment]
Umgesetzt (siehe GitHub).

**Comment by Flozi95** [comment]
Dann werde ich die Parser Projects und Website auch upgraden?

**Comment by chrishensel** [comment]
Das wär super, ja :)
