### ISSUE TITLE
ASP MVC

### ISSUE THREAD

**Issue by smartmeter** [OpenFireSource/AlarmWorkflow#145]
Hi, I am trying to adapt this to asp MVC for a simple notifications and alerts feature. Can you post a simple snippet on how to do a long running workflow...

For e.g. simplease case or _purchase approval_

**Comment by Flozi95** [comment]
Imho you're wrong here. This app is for parsing fire alarm information for german fire brigades,

**Comment by smartmeter** [comment]
ohh sorry :)   :+1:
