### ISSUE TITLE
Fax von Netzlaufwerk - Error wenn nicht Verfügbar

### ISSUE THREAD

**Issue by alex-doe** [OpenFireSource/AlarmWorkflow#147]
Hi,

wenn als Faxquelle ein Netzwerklaufwerk eingestellt ist, und das Netzlaufwerk zwischendurch nicht verfügbar war, gibt es eine System.IO.IOException. Diese führt zum sofortigen beenden des Fax IAlarmSource Threads. Sprich es muss der Service durchgestartet werden damit die Faxquelle wieder funktioniert.

PR #150

**Comment by alex-doe** [comment]
Im laufenden IAlarmSource Thread werden vom angegebenen Laufwerk alle Files enummeriert.
`FileInfo[] files = _faxPath.GetFiles("*.*", SearchOption.TopDirectoryOnly)`

Wenn das Laufwerk, z.B. auf Grund von Netzwerkproblemen oder Wartungsarbeiten, in diesem Moment nicht verfügbar ist kommt es zu einer `System.IO.IOException`.

Die existierenden aufrufe der Funktion `EnsureDirectoriesExist();` helfen hier leider nicht. Da diese nur beim Initialisieren und dem abarbeiten eines neuen Faxbildes aufgerufen wird.

Im Falle der og. unhandled Exception bricht der IAlarmSource Thread ab und wird nicht neugestartet. Dies kann nur durch einen Dienst Neustart bewerkstelligt werden.

Mein PR #150 sichert die Operationen im Thread gegen unbehandelte Exceptions ab. Dadurch bleibt der Thread immer "am Leben". Egal welche Art von Exception im Thread auftritt.

Alternativ ist es auch möglich, bei jedem Roundtrip des Threads, die Methode `EnsureDirectoriesExist()` vor dem enummerieren des `_faxPath` Verzeichnisses aufzurufen. Dann würde eine `System.IO.IOException` abgefangen werden.

**Comment by Flozi95** [comment]
Schreibst halt massig Logeinträge wenn der Server z.b. mal 10 Minuten offline ist...

**Comment by Flozi95** [comment]
2000ms => 2 Sekunden => 30 mal pro Minute => 300 Logeinträge. 
Das ist das was ich zu denken gebe.

**Comment by alex-doe** [comment]
Da gebe ich dir vollkommen Recht.
Habe einen, nicht höllisch eleganten, Lösungsvorschlag.
Ein bool Flag um den Errorstate zu markieren. Und dann das Logging nur einmal ausführen bis ein erfolgreicher Durchlauf stattgefunden hat.
https://gist.github.com/alex-doe/f1dc3ff558e62f48837c5a43c33382fd

**Comment by Flozi95** [comment]
Also wenn dann bitte zumindest aus dem catch(Exception e) eine IOException machen. (Bin gerade am Überlegen wie ich feststellen kann obs wirklich immer die gleiche is) Dann kann ich damit leben. Die Zeilen in der try{} dann noch einrücken ;) (Mal autoformat von VS ... außer von dem kamen die von davor?)

**Comment by alex-doe** [comment]
Autoformat habe ich schon mal behoben.
Magst du dir mal den gist mal anschauen?
https://gist.github.com/alex-doe/58ae79b78816d6a33956b4014e055190
Ich habe eine Klasse gebaut die es ermöglicht Errors zu sammeln und diese dann nach einem vorgegebenen Intervall zu loggen.
Das müsste ein deutlich eleganterer Ansatz sein hier zu Loggen.
Was meinst du?

**Comment by Flozi95** [comment]
Die Idee gefällt mir gut. 
Über die Namen von Klassen kann man noch diskutieren ;) TimedException würde ich bevorzugen. 
Public Methoden/Klassen bitte noch kurz dokumentieren.
Pack mal die Klassen in die entsprechenden namespaces.

**Comment by alex-doe** [comment]
Ich habe gerade die Klasse aus dem gist eingebaut.
Hoffentlich war es nicht falsch diese neben den anderen Logger Klassen in `AlarmWorkflow.Shared.Diagnostics` zu platzieren.
Die XML-doc habe ich soweit geschrieben.

Zum Problem mit dem überlauf der Liste. Ich habe als "Sicherheit" eine Methode zum reset der Liste eingebaut. Diese wird beim ersten erfolgreichen Durchlauf ausgeführt.

Gerne kann ich die Klassennamen noch anpassen ;-)

**Comment by alex-doe** [comment]
So jetzt alles in einem PR #151
