### ISSUE TITLE
Foren-E-Mail

### ISSUE THREAD

**Issue by gitdjango** [OpenFireSource/AlarmWorkflow#165]
Hallo ich hab ein Problem mit dem Forum (http://www.openfiresource.de/index.php) und kann mich nicht mehr anmelden. Ich hab's über die E-Mail-Adresse "forum@openfiresource.de" versucht, diese funktioniert aber auch nicht.

**Comment by ForrestFalcon** [comment]
Hm, komisch. Versuch bitte mal alle Daten (besonders Cookies) der Webseite zu löschen. 
Welche Fehlermeldung kommt denn, bzw. wie äußert sich der Fehler? (User nicht gefunden oder andersweitig?)

**Comment by gitdjango** [comment]
Hatte vergessen die Fehlermeldung mit anzuhängen:
> Der angegebene Benutzername ist derzeit inaktiv. Wenn du weiterhin Probleme bei der Aktivierung deines Benutzerkontos hast, wende dich bitte an die Board-Administration.

Cookies usw. hatte ich bereits gelöscht. Hab es jetzt nochmal gemacht. Hat nichts geändert.

**Comment by ForrestFalcon** [comment]
Okay, möchtest du mir bitte kurz deinen Benutzer sagen? Dann werde ich kurz nachschauen :)

**Comment by Effendi112** [comment]
Hallo,

ich habe das gleiche Problem, Benutzername "Redhawk112".
Ich bekomme auch keinen Aktivierungsschlüssel und an die Mailadresse kann ich auch nichts schicken.
Wäre schön wenn ich Zugang bekommen könnte.

**Comment by gitdjango** [comment]
Hallo hab die E-Mail komplett übersehen. Mein Benutzerkonto ist „fflue“.

 

Viele Grüße

 

Stefan

 

Von: Stieglitz [mailto:notifications@github.com] 
Gesendet: Montag, 16. Juli 2018 23:26
An: OpenFireSource/AlarmWorkflow <AlarmWorkflow@noreply.github.com>
Cc: gitdjango <stefan.witossek@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [OpenFireSource/AlarmWorkflow] Foren-E-Mail (#165)

 

Okay, möchtest du mir bitte kurz deinen Benutzer sagen? Dann werde ich kurz nachschauen :)

**Comment by ForrestFalcon** [comment]
Hallo @gitdjango, wir werden voraussichtlich am Donnerstag/Freitag das forum umstellen. Danach sollte es mit den Mails wieder funktionieren.

**Comment by ForrestFalcon** [comment]
Das neue Forum ist online. Somit sollte es zu keinen Problemen mit der E-Mail mehr kommen.
